const quotes = [
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "Your time is limited, don't waste it living someone else's life.",
  "The best way to predict the future is to create it.",
  "Efficiency is doing better what is already being done.",
  "The warehouse is the heartbeat of the supply chain.",
  "In the warehouse, teamwork is the key to success.",
  "Small steps every day lead to big results.",
  "A well-organized warehouse reflects a well-organized mind.",
  "Quality means doing it right when no one is looking.",
  "Safety is not just a priority, it’s a core value.",
  "Your work in the warehouse keeps the world moving.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "A smooth warehouse operation is the sign of a strong team.",
  "Order in the warehouse brings order to the world.",
  "In the warehouse, every detail counts.",
  "Behind every successful delivery is a well-organized warehouse.",
  "The strength of a warehouse team is in their unity.",
  "Organization is the foundation of efficiency.",
  "A safe warehouse is a productive warehouse.",
  "Precision in the warehouse leads to perfection in the product.",
  "The warehouse is where the magic of logistics begins.",
  "Every pallet counts; every second counts.",
  "In the warehouse, the key to success is consistency.",
  "Your hard work in the warehouse ensures smooth operations everywhere else.",
  "A well-stocked warehouse is the sign of a well-run business.",
  "Teamwork divides the task and multiplies the success in the warehouse.",
  "Warehouse excellence is the backbone of the supply chain.",
  "Your dedication in the warehouse makes everything else possible.",
];

export default quotes;
